name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior, including CRD manifests if applicable.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Include operator logs and kubectl output.
    validations:
      required: true
  - type: input
    id: k8s-version
    attributes:
      label: Kubernetes Version
      placeholder: "e.g., 1.28"
    validations:
      required: true
  - type: input
    id: operator-version
    attributes:
      label: Operator Version
      placeholder: "e.g., 0.2.0"
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
