apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: streamline-system

resources:
  - namespace.yaml
  - crds/
  - rbac/service-account.yaml
  - rbac/cluster-role.yaml
  - rbac/cluster-role-binding.yaml
  - operator.yaml

commonLabels:
  app.kubernetes.io/part-of: streamline
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/streamlinelabs/streamline-operator
    newTag: "0.3.0"
