//! Deterministic CRD manifest generation.
//!
//! The `kube-derive` annotations on the types in [`crate::crd`] are the single
//! source of truth for the CustomResourceDefinitions this operator ships. This
//! module renders those definitions to YAML so that:
//!
//! * `deploy/crds/*.yaml` can be regenerated (`make generate-crds`) instead of
//!   being hand-maintained and drifting from the Rust structs, and
//! * the release pipeline can publish (and verify) the exact manifests that
//!   match the binary being released.
//!
//! Rendering is deterministic: the ordering of every map in the emitted schema
//! comes from `schemars`' `BTreeMap` representation, and no timestamps, build
//! metadata, or environment values are included. Generating twice on two
//! machines with the same toolchain produces byte-identical output, which is
//! what makes the drift test in `tests/crd_manifests.rs` meaningful.

use crate::crd::{
    StreamlineBackup, StreamlineBranch, StreamlineCluster, StreamlineContract, StreamlineEdge,
    StreamlineMemory, StreamlineTopic, StreamlineUser,
};
use crate::error::{OperatorError, Result};
use k8s_openapi::apiextensions_apiserver::pkg::apis::apiextensions::v1::CustomResourceDefinition;
use kube::CustomResourceExt;

/// Whether a generated CRD is backed by a controller in this operator.
///
/// CRDs without a controller are still generated (they are part of the crate's
/// public schema surface) but are deliberately *not* installed by
/// `deploy/crds/kustomization.yaml`, not granted RBAC, and not started in
/// `main.rs`: installing them would advertise support the operator does not
/// implement, and starting a controller for them would spin a reconcile loop
/// that can only ever fail or lie.
///
/// [`Reconciliation::None`] carries the reason so the generated manifest, the
/// docs, and the tests all quote the same justification. Re-enabling a kind
/// means editing this metadata, which is what makes the guard tests in
/// `tests/crd_manifests.rs` impossible to bypass by accident.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reconciliation {
    /// A controller in this operator reconciles the resource.
    By(&'static str),
    /// No controller reconciles the resource — schema only. The payload is the
    /// reason, rendered into the manifest header.
    None(&'static str),
}

/// A single rendered CRD manifest.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedCrd {
    /// Custom resource kind, e.g. `StreamlineCluster`.
    pub kind: &'static str,
    /// Rust module the schema is derived from, e.g. `src/crd/cluster.rs`.
    pub source: &'static str,
    /// Which controller (if any) reconciles the resource.
    pub reconciliation: Reconciliation,
    /// Metadata name of the CRD, e.g. `streamlineclusters.streamline.io`.
    pub metadata_name: String,
    /// File name used under `deploy/crds/`.
    pub file_name: String,
    /// Rendered YAML document, including the generation header.
    pub yaml: String,
}

impl GeneratedCrd {
    /// Whether this CRD is part of the installed (kustomize) manifest set.
    pub fn is_installed(&self) -> bool {
        matches!(self.reconciliation, Reconciliation::By(_))
    }
}

/// Directory (relative to the repository root) holding the generated manifests.
pub const CRD_DIR: &str = "deploy/crds";

fn render(
    kind: &'static str,
    source: &'static str,
    reconciliation: Reconciliation,
    crd: CustomResourceDefinition,
) -> Result<GeneratedCrd> {
    let metadata_name = crd.metadata.name.clone().ok_or_else(|| {
        OperatorError::Serialization(format!("generated CRD for {kind} has no metadata.name"))
    })?;

    let body = serde_yaml::to_string(&crd)
        .map_err(|e| OperatorError::Serialization(format!("failed to render {kind} CRD: {e}")))?;

    let reconciled_by = match reconciliation {
        Reconciliation::By(controller) => {
            format!("# Reconciled by: {controller} (installed via {CRD_DIR}/kustomization.yaml).")
        }
        Reconciliation::None(reason) => format!(
            "# Reconciled by: nothing — schema only, deliberately NOT installed by\n\
             # {CRD_DIR}/kustomization.yaml, NOT granted RBAC, and NOT started by the\n\
             # operator, so it cannot advertise unsupported behaviour.\n\
             # Reason: {reason}"
        ),
    };

    let yaml = format!(
        "# Generated by `streamline-operator --generate-crds`. DO NOT EDIT.\n\
         #\n\
         # Source of truth: {source} (`#[kube(...)]` annotations).\n\
         # Regenerate with: make generate-crds\n\
         {reconciled_by}\n\
         {body}"
    );

    Ok(GeneratedCrd {
        kind,
        source,
        reconciliation,
        metadata_name,
        file_name: format!("{}-crd.yaml", kind.to_lowercase()),
        yaml,
    })
}

/// Render every CRD this crate defines, in a stable order.
pub fn generated_crds() -> Result<Vec<GeneratedCrd>> {
    Ok(vec![
        render(
            "StreamlineCluster",
            "src/crd/cluster.rs",
            Reconciliation::By("ClusterController"),
            StreamlineCluster::crd(),
        )?,
        render(
            "StreamlineTopic",
            "src/crd/topic.rs",
            Reconciliation::By("TopicController"),
            StreamlineTopic::crd(),
        )?,
        render(
            "StreamlineUser",
            "src/crd/user.rs",
            Reconciliation::By("UserController"),
            StreamlineUser::crd(),
        )?,
        render(
            "StreamlineBranch",
            "src/crd/branch.rs",
            Reconciliation::None(
                "the Streamline server's branch API is behind the non-default `branches` \
                 cargo feature (absent from both `lite` and `full`) and takes \
                 {base_topic, name, base_offsets, created_by} with `<base_topic>:<name>` \
                 identifiers, which this CRD cannot express",
            ),
            StreamlineBranch::crd(),
        )?,
        render(
            "StreamlineContract",
            "src/crd/contract.rs",
            Reconciliation::None(
                "the Streamline server exposes POST /api/v1/contracts/{validate,apply} taking \
                 {contract: {topic, version, schema_id, assertions}, partition, value}; there is \
                 no POST /api/v1/contracts and no schema/compatibility/bindTopics contract this \
                 CRD could apply",
            ),
            StreamlineContract::crd(),
        )?,
        render(
            "StreamlineMemory",
            "src/crd/memory.rs",
            Reconciliation::None(
                "the Streamline server's memory API is behind the non-default `agent-memory` \
                 cargo feature and is a remember/recall endpoint, not a provisioning API; a \
                 controller could only create plain topics and then report memory tiers Ready \
                 that nothing implements",
            ),
            StreamlineMemory::crd(),
        )?,
        render(
            "StreamlineBackup",
            "src/crd/backup.rs",
            Reconciliation::None("the Streamline server exposes no backup or restore API"),
            StreamlineBackup::crd(),
        )?,
        render(
            "StreamlineEdge",
            "src/crd/edge.rs",
            Reconciliation::None(
                "the Streamline server's edge sync support is behind the non-default `edge` \
                 cargo feature and exposes no endpoint this CRD could reconcile",
            ),
            StreamlineEdge::crd(),
        )?,
    ])
}

/// Render the installed CRDs as a single multi-document YAML manifest.
///
/// This is what the release pipeline attaches to a release: applying it is
/// equivalent to `kubectl apply -k deploy/crds/`.
pub fn render_installed_manifest() -> Result<String> {
    let mut out = String::new();
    for crd in generated_crds()?.iter().filter(|c| c.is_installed()) {
        if !out.is_empty() {
            out.push_str("---\n");
        }
        out.push_str(&crd.yaml);
    }
    Ok(out)
}

/// Write one manifest per CRD into `dir`, returning the files written.
///
/// Existing files are overwritten; unrelated files are left untouched so the
/// caller (and the drift test) can detect strays explicitly.
pub fn write_crds(dir: &std::path::Path) -> Result<Vec<std::path::PathBuf>> {
    std::fs::create_dir_all(dir)
        .map_err(|e| OperatorError::Internal(format!("failed to create {}: {e}", dir.display())))?;

    let mut written = Vec::new();
    for crd in generated_crds()? {
        let path = dir.join(&crd.file_name);
        std::fs::write(&path, &crd.yaml).map_err(|e| {
            OperatorError::Internal(format!("failed to write {}: {e}", path.display()))
        })?;
        written.push(path);
    }
    Ok(written)
}

#[cfg(test)]
mod tests {
    // unwrap/expect are acceptable in tests; the crate-wide lint targets production code.
    #![allow(clippy::unwrap_used, clippy::expect_used)]
    use super::*;

    #[test]
    fn generation_is_deterministic() {
        let first = generated_crds().unwrap();
        let second = generated_crds().unwrap();
        assert_eq!(first, second);
    }

    #[test]
    fn every_crd_has_a_stable_file_name_and_metadata_name() {
        for crd in generated_crds().unwrap() {
            assert_eq!(
                crd.file_name,
                format!("{}-crd.yaml", crd.kind.to_lowercase())
            );
            assert!(
                crd.metadata_name.ends_with(".streamline.io"),
                "{} has unexpected metadata name {}",
                crd.kind,
                crd.metadata_name
            );
        }
    }

    #[test]
    fn rendered_yaml_parses_as_a_custom_resource_definition() {
        for crd in generated_crds().unwrap() {
            let parsed: CustomResourceDefinition = serde_yaml::from_str(&crd.yaml)
                .unwrap_or_else(|e| panic!("{} does not parse as a CRD: {e}", crd.kind));
            assert_eq!(parsed.spec.group, "streamline.io");
            assert_eq!(
                parsed.metadata.name.as_deref(),
                Some(crd.metadata_name.as_str())
            );
            assert!(
                !parsed.spec.versions.is_empty(),
                "{} must declare at least one version",
                crd.kind
            );
            for version in &parsed.spec.versions {
                assert!(
                    version.schema.is_some(),
                    "{} version {} must carry an OpenAPI schema",
                    crd.kind,
                    version.name
                );
            }
        }
    }

    #[test]
    fn installed_manifest_contains_only_reconciled_kinds() {
        let manifest = render_installed_manifest().unwrap();
        for crd in generated_crds().unwrap() {
            let mentioned = manifest.contains(&format!("kind: {}\n", crd.kind));
            assert_eq!(
                mentioned,
                crd.is_installed(),
                "{} installed={} but manifest mention={}",
                crd.kind,
                crd.is_installed(),
                mentioned
            );
        }
    }

    #[test]
    fn installed_manifest_documents_are_separated() {
        let manifest = render_installed_manifest().unwrap();
        let installed = generated_crds()
            .unwrap()
            .into_iter()
            .filter(GeneratedCrd::is_installed)
            .count();
        assert_eq!(manifest.matches("\n---\n").count(), installed - 1);
        assert!(manifest.starts_with("# Generated by"));
    }

    #[test]
    fn unreconciled_crds_are_marked_as_not_installed_with_a_reason() {
        let mut unreconciled = 0;
        for crd in generated_crds().unwrap() {
            let Reconciliation::None(reason) = crd.reconciliation else {
                continue;
            };
            unreconciled += 1;

            assert!(
                crd.yaml.contains("NOT installed"),
                "{} must document that it is not installed",
                crd.kind
            );
            assert!(
                crd.yaml.contains("NOT granted RBAC"),
                "{} must document that it holds no RBAC",
                crd.kind
            );
            assert!(
                !reason.trim().is_empty(),
                "{} must justify why nothing reconciles it",
                crd.kind
            );
            assert!(
                crd.yaml.contains(reason),
                "{}'s reason must reach the generated manifest",
                crd.kind
            );
        }
        assert!(
            unreconciled > 0,
            "expected at least one schema-only CRD to guard"
        );
    }

    /// The exact set of unsupported kinds is pinned. Adding a controller for
    /// one of these is a deliberate act that has to update this list, the
    /// kustomization, and the RBAC together.
    #[test]
    fn the_unsupported_kinds_are_exactly_the_ones_core_cannot_back() {
        let unreconciled: Vec<&'static str> = generated_crds()
            .unwrap()
            .iter()
            .filter(|c| matches!(c.reconciliation, Reconciliation::None(_)))
            .map(|c| c.kind)
            .collect();

        assert_eq!(
            unreconciled,
            vec![
                "StreamlineBranch",
                "StreamlineContract",
                "StreamlineMemory",
                "StreamlineBackup",
                "StreamlineEdge",
            ]
        );
    }

    #[test]
    fn the_installed_kinds_are_exactly_the_supported_ones() {
        let installed: Vec<&'static str> = generated_crds()
            .unwrap()
            .iter()
            .filter(|c| c.is_installed())
            .map(|c| c.kind)
            .collect();

        assert_eq!(
            installed,
            vec!["StreamlineCluster", "StreamlineTopic", "StreamlineUser"]
        );
    }
}
